### ISSUE TITLE
gpt-4o-mini as the default model for explanation?

### ISSUE THREAD

**Issue by kuopenx** [BuilderIO/ai-shell#121]
Since gpt-4o-mini was released out now and it's way cheaper than gpt-3.5-turbo. It would be nice to set 4o-mini as the default model for explanation, or offer an additional option for choosing the default model.

**Comment by steve8708** [comment]
good idea, PRs always valued! I would check first to make sure it doesn't have requirements like gpt-4 of having spent at least $20 or whatever openai has, if it doesn't i agree it would be great to get it as the new default
