### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by ZeldOcarina** [BuilderIO/ai-shell#13]
I got a 429 back and it was just blobbed on the screen, hard to read what was happening.
Also, it's weird I got a 429 back as this has been my first query!

![image](https://user-images.githubusercontent.com/42982095/230728482-f238d28b-0e1d-44af-b202-e23601db12ee.png)

**Comment by AlaEddineBoughanmmi** [comment]
I got the same issue (error code 429)! 

near the end of the error message there is this:

![image](https://user-images.githubusercontent.com/37481319/230746727-c4e67fed-6633-4643-a4ae-a74bb12bd8af.png)

same discussion here https://github.com/BuilderIO/ai-shell/issues/6

**Comment by steve8708** [comment]
Released better error handling in `0.0.18`
