### ISSUE TITLE
zsh weird error

### ISSUE THREAD

**Issue by ZeldOcarina** [BuilderIO/ai-shell#14]
Sorry to open two issues but maybe you'd like to know.

I've done all the installation steps and I get a version out of the software, I've set the API key etc. but I get this zsh error, or a 429 on the list prompt as stated on the other issue.

Thanks for your help!!

![image](https://user-images.githubusercontent.com/42982095/230728648-9efec62b-ea45-421a-a7e4-eff9d1f99b70.png)

**Comment by AlaEddineBoughanmmi** [comment]
zsh is interpreting the ? in the prompt as a globbing wildcard

To prevent this wrap the prompt in quotes: "what is my ip address?"

![image](https://user-images.githubusercontent.com/37481319/230746282-927d4d68-5b5e-4c1e-90f5-be29bfae28fb.png)

you can also use the noglob.

![image](https://user-images.githubusercontent.com/37481319/230746389-7bc87e5c-59d6-4d2f-b928-03f942bdfe65.png)

**Comment by steve8708** [comment]
ah! I should add this to the readme, that a safer way if you want to use special chars that can be handled by various shells to put it in quotes

another option is to use an alias like the copilot CLI:


    ### Setup alias convenience commands 

    You can run GitHub Copilot CLI directly using `github-copilot-cli`, but we recommend you install the `??`, `git?`, and `gh?`  commands in your shell.
    These are not only more convenient to type, but also [provide added features](#whats-the-point-of-the-eval-and-alias- stuff).
    To install them, run the following command:

    ```bash
    eval "$(github-copilot-cli alias -- "$0")"
    ```


perhaps we should update the readme accordingly. interested in contributing a PR to the readme?

**Comment by steve8708** [comment]
added a quick note to the readme, happy to take suggestions to improve it
