### ISSUE TITLE
Allow language choice for responses

### ISSUE THREAD

**Issue by Delatorrea** [BuilderIO/ai-shell#16]
I have noticed that Explanation currently only responds in English. It would be possible to allow users to choose the language of the response to make it more user-friendly for more people.

**Comment by steve8708** [comment]
Good idea. We could make this a config, and add one simple line to the prompt like

```
Please reply in ${language}
```

**Comment by steve8708** [comment]
Interested in sending a PR?

**Comment by Delatorrea** [comment]
I am interested in sending PR yes. Thought I'd start adding unit tests and refactoring, what do you think?

**Comment by steve8708** [comment]
That would be great!

**Comment by sfmqrb** [comment]
Is anyone working on this?

**Comment by qihangnet** [comment]
@steve8708 I have sent a PR

**Comment by steve8708** [comment]
Released in version `0.1.20`!
