### ISSUE TITLE
Add option for silent mode 

### ISSUE THREAD

**Issue by AlaEddineBoughanmmi** [BuilderIO/ai-shell#19]
would be nice to offer the option for a silent mode so we don't output the explanation 
 <pre> 
 $ ai --silent  list all log files
 | find . -name "*.log"
 | [<ins>run</ins>, revise, cancel]
 </pre>

**Comment by soumilroy** [comment]
seconded! Would it be a good approach to set it in config?

`ai-shell config set SILENT_MODE=true|false`

**Comment by soumilroy** [comment]
Made a PR on this

https://user-images.githubusercontent.com/42084105/230769049-e85950b2-b45c-44ea-8ff2-b1b1a7d88aa8.mov

**Comment by steve8708** [comment]
Great! I love the idea of a config and flag ideally. I'm not seeing your PR though, did you submit it here? https://github.com/BuilderIO/ai-shell/pulls

**Comment by AlaEddineBoughanmmi** [comment]
I think using a flag -s or --silent (similar/opposite to --verbose on linux) is more flexible so w dont have to change the config regularly 
and type a long command like this very often 
```ai-shell config set SILENT_MODE=true|false```

or we can have both options!

**Comment by AlaEddineBoughanmmi** [comment]
I can submit a PR if you haven't added this feature yet @soumilroy?

**Comment by steve8708** [comment]
Great, yeah I love the idea of supporting both

**Comment by soumilroy** [comment]
@steve8708 submitted. Sorry I forgot to push last night.

@AlaEddineBoughanmmi Agreed on having both options :)

**Comment by steve8708** [comment]
Merged, and released in `0.1.6`!
