### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by prbrody** [BuilderIO/ai-shell#23]
I get this error when trying to use this system even though I think I successfully followed all installation instructions. And suggestions?

<img width="572" alt="Screenshot 2023-04-09 at 11 21 10" src="https://user-images.githubusercontent.com/1174708/230789919-f8ed3d57-1d2d-49d7-964d-141c7ec43b30.png">

**Comment by steve8708** [comment]
Ah! This is likely a [429 error](https://github.com/builderio/ai-shell#429-error). Will fix the JSON handling of this

**Comment by steve8708** [comment]
Should be fixed now in `v0.1.2` - if you update to the latest and try again you should see a proper error message that tells you what exact is wrong. 

Thanks for reporting!

**Comment by prbrody** [comment]
Thank you! I'll try it when I land.  I'm on airplanes for the next 18 hours with very slow wifi.  Thanks for replying.

**Comment by prbrody** [comment]
It worked!!



Paul Brody [Contact info link – vCard]
<https://www.icloud.com/iclouddrive/0ktaXa4YckPcVSOlgw8irNxdQ#Paul_Brody_-_vCard>

View Availability & Book Appointments
***@***.***/bookings/>
