### ISSUE TITLE
Support chinese?

### ISSUE THREAD

**Issue by liuke2016** [BuilderIO/ai-shell#27]
Support chinese?

**Comment by steve8708** [comment]
Duplicates #16

**Comment by steve8708** [comment]
Open to pull requests if you’d like to add this!

**Comment by steve8708** [comment]
Another thing that might be required to use chinese well is to use a model trained in chinese by supporting additional models #17

**Comment by qihangnet** [comment]
Just letting you know that I've sent PR #62 !
Once this PR is merged, you will get a new ai-shell like the cool animation below:
![ai-shell-multi-languages](https://user-images.githubusercontent.com/1784873/235330029-0a3b394c-d797-41d6-8717-9a6b487f1ae8.gif)
