### ISSUE TITLE
Stream responses from OpenAI API

### ISSUE THREAD

**Issue by steve8708** [BuilderIO/ai-shell#3]
Instead of making the user wait for the entire output of the shell code or description to be finished to see it, it would be great to stream the response word by word to the terminal like done on sites like chatgpt

**Comment by steve8708** [comment]
how this can be done:

```
  const res = await openai.createChatCompletion({
    messages: [{ content: prompt }],
    stream: true,
  }, { responseType: "stream" });
```

now the response will be a text stream. we could stream the response to the CLI output with `process.stdout.write`

**Comment by Iwasherd** [comment]
PR [https://github.com/BuilderIO/ai-shell/pull/12]
