### ISSUE TITLE
Azure OpenAI service support

### ISSUE THREAD

**Issue by lzhgus** [BuilderIO/ai-shell#37]
Would be nice to offer an option to use Azure OpenAI service

**Comment by steve8708** [comment]
reopenning as it seems we need different logic for key validation if we detect an azure url

**Comment by Guilloperez** [comment]
Bien

**Comment by crystoneme** [comment]
but, still says '✖ Invalid config property OPENAI_KEY: Must start with "sk-"' if config with Azure API Key

**Comment by lzhgus** [comment]
@steve8708 This is because we cannot determine whether the proxy endpoint is for Azure or OpenAI without introducing another configuration setting such as "USEAZURE: boolean". Therefore, I believe it would be better to remove the validation of openai keys. Please review, thanks!
