### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by steve8708** [BuilderIO/ai-shell#4]
Right now this assumes you use bash on mac or Linux. Would be great to support windows too, eg by specifying that in the prompt we generate when detected

**Comment by haraldreingruber** [comment]
I am interested in trying to contribute Windows PowerShell support.

How would you specify it in the prompt?
Could you provide a first hint/starting point to integrate this feature?

**Comment by Ezzahhh** [comment]
I made an attempt on this issue but may need some testers and review on the code (is it too simplistic?)

**Comment by steve8708** [comment]
tbh this is exactly what I was anticipating was needed. if we find it is flakey at all, I've has some success with being more dramatic in the prompt. like adding

```
IMPORTANT: be sure the shell script works with ${shellType}.
```

**Comment by steve8708** [comment]
Just released v0.0.13 with this update!

**Comment by zeratax** [comment]
this seems to add `powershell` to every command, basically executing it in the context of a new powershell?

E.g. I do `$ ai get all pdfs in this directory`
which then returns:
```ps1
 powershell
Get-ChildItem -Filter "*.pdf"
```

which will run this command in my user directory, not the current dir and also requires `Set-ExecutionPolicy RemoteSigned`

**Comment by zeratax** [comment]
So I solved this by adding an example:
https://github.com/BuilderIO/ai-shell/blame/28e19f0530d3a609c98a751ba4abd2ea7289d343/src/helpers/completion.ts#L269

```
Only reply with the single line command surrounded by three backticks. It must be able to be directly run in the target shell. Do not include any other text.

Example: \`\`\`curl -s ifconfig.me\`\`\`

Make sure the command runs on ${getOperationSystemDetails()} operating system.
```

but i haven't tested this much
