### ISSUE TITLE
Crash on versions 0.1.14 and up

### ISSUE THREAD

**Issue by Irian-Adappty** [BuilderIO/ai-shell#64]
I'm on Linux Mint distribution and the package works great on version 0.1.13 but any higher version crashes on any command.
Output of any command I try starting with 'ai':

```
cat: /etc/upstream-release: Is a directory
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: cat /etc/*release
cat: /etc/upstream-release: Is a directory

    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at osReleaseSync (/home/irian-adappty/.nvm/versions/node/v19.9.0/lib/node_modules/@builder.io/ai-shell/node_modules/@nexssp/os/lib/distro.js:21:12)
    at module.exports.get (/home/irian-adappty/.nvm/versions/node/v19.9.0/lib/node_modules/@builder.io/ai-shell/node_modules/@nexssp/os/lib/distro.js:47:25)
    at Object.name (/home/irian-adappty/.nvm/versions/node/v19.9.0/lib/node_modules/@builder.io/ai-shell/node_modules/@nexssp/os/legacy.js:4:20)
    at getOperationSystemDetails (file:///home/irian-adappty/.nvm/versions/node/v19.9.0/lib/node_modules/@builder.io/ai-shell/dist/cli.mjs:488:13)
    at file:///home/irian-adappty/.nvm/versions/node/v19.9.0/lib/node_modules/@builder.io/ai-shell/dist/cli.mjs:493:37
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(475) [Uint8Array] [
       68,  73,  83,  84,  82,  73,  66,  95,  73,  68, 61,  76,
      105, 110, 117, 120,  77, 105, 110, 116,  10,  68, 73,  83,
       84,  82,  73,  66,  95,  82,  69,  76,  69,  65, 83,  69,
       61,  50,  48,  46,  51,  10,  68,  73,  83,  84, 82,  73,
       66,  95,  67,  79,  68,  69,  78,  65,  77,  69, 61, 117,
      110,  97,  10,  68,  73,  83,  84,  82,  73,  66, 95,  68,
       69,  83,  67,  82,  73,  80,  84,  73,  79,  78, 61,  34,
       76, 105, 110, 117, 120,  32,  77, 105, 110, 116, 32,  50,
       48,  46,  51,  32,
      ... 375 more items
    ],
    Buffer(43) [Uint8Array] [
       99,  97, 116,  58,  32,  47, 101, 116,  99,
       47, 117, 112, 115, 116, 114, 101,  97, 109,
       45, 114, 101, 108, 101,  97, 115, 101,  58,
       32,  73, 115,  32,  97,  32, 100, 105, 114,
      101,  99, 116, 111, 114, 121,  10
    ]
  ],
  pid: 55561,
  stdout: Buffer(475) [Uint8Array] [
     68,  73,  83,  84,  82,  73,  66,  95,  73,  68, 61,  76,
    105, 110, 117, 120,  77, 105, 110, 116,  10,  68, 73,  83,
     84,  82,  73,  66,  95,  82,  69,  76,  69,  65, 83,  69,
     61,  50,  48,  46,  51,  10,  68,  73,  83,  84, 82,  73,
     66,  95,  67,  79,  68,  69,  78,  65,  77,  69, 61, 117,
    110,  97,  10,  68,  73,  83,  84,  82,  73,  66, 95,  68,
     69,  83,  67,  82,  73,  80,  84,  73,  79,  78, 61,  34,
     76, 105, 110, 117, 120,  32,  77, 105, 110, 116, 32,  50,
     48,  46,  51,  32,
    ... 375 more items
  ],
  stderr: Buffer(43) [Uint8Array] [
     99,  97, 116,  58,  32,  47, 101, 116,  99,
     47, 117, 112, 115, 116, 114, 101,  97, 109,
     45, 114, 101, 108, 101,  97, 115, 101,  58,
     32,  73, 115,  32,  97,  32, 100, 105, 114,
    101,  99, 116, 111, 114, 121,  10
  ]
}

```

Things I've tried:

- Installed several versions and all of them crash if it's higher than 0.1.13 (have tried 0.1.14, 16 and 20)
- Tried with the following node versions applying fix of [this answer of #48](https://github.com/BuilderIO/ai-shell/issues/48#issuecomment-1509485464): Node v19.9.0, 18.16.0 and 16.19.0

My OS details:

```
Distributor ID:	Linuxmint
Description:	Linux Mint 20.3
Release:	20.3
Codename:	una

Linux linux 5.4.0-147-generic #164-Ubuntu SMP Tue Mar 21 14:23:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Video of the issue: https://contecnika-my.sharepoint.com/:v:/g/personal/irian_caigo_es/EU1juhHdlB1BugdA3iTy0hAB5TRO_mNWaf9pgVwP8ONa2Q?e=IDzBxM

**Comment by steve8708** [comment]
@qihangnet  this seems to have come from your update https://github.com/BuilderIO/ai-shell/pull/62 would you be able to take a look at this?

**Comment by qihangnet** [comment]
@steve8708 He said that this issue has been present since version 0.13, and it should not be caused by my PR.
the error message is `cat: /etc/upstream-release: Is a directory`.
Is this an error command generated by AI-Shell after executing the prompt?
@Irian-Adappty Can you show me your prompt?

**Comment by Irian-Adappty** [comment]
Sure @qihangnet here's a video of the process and how it gives error: https://contecnika-my.sharepoint.com/:v:/g/personal/irian_caigo_es/EU1juhHdlB1BugdA3iTy0hAB5TRO_mNWaf9pgVwP8ONa2Q?e=IDzBxM

**Comment by qihangnet** [comment]
@Irian-Adappty I have found the cause: referencing package @nexssp/os in PR #49 .
The method for determining the Linux system distribution in [this line of code](https://github.com/nexssp/os/blob/a5369b5b9ce5c6f58c4484de5c9dfab0e84f1f67/lib/distro.js#LL21C38-L21C38) has an issue.
This line of code should be

``` js
return execSync('cat /etc/os-release').toString().trim()
```

**Comment by qihangnet** [comment]
I have submitted a PR for `@nexssp/os`: https://github.com/nexssp/os/pull/6. 
After it is merged and released, I will update the package version of ai-shell to fix this bug.

**Comment by qihangnet** [comment]
Additionally, a friendly reminder: @Irian-Adappty please be mindful of protecting your OpenAI API KEY in the video and do not expose it in public to avoid being misused. 😄

**Comment by Irian-Adappty** [comment]
Oh great spotting @qihangnet !

Command `cat /etc/*-release` outputs 1 file and 1 directory: `/etc/os-release` and `/etc/upstream-release` which is a directory and crashes. So it should be as you say: `cat /etc/os-release`.

As per the API key don't worry, I've revoked it before posting the video (it's shown in the last second of it actually)

**Comment by qihangnet** [comment]
@Irian-Adappty @steve8708 
PR https://github.com/BuilderIO/ai-shell/pull/72 will fix it.

**Comment by steve8708** [comment]
Released in v0.1.21!

**Comment by qihangnet** [comment]
That's the speed of a  🚀 ! 😄

**Comment by Irian-Adappty** [comment]
It works! Many thanks! This has been fixed very quickly and I can now use the latest version 😋

![image](https://user-images.githubusercontent.com/89632138/236495617-916ce2db-96a9-4db8-aaf4-8462c4b79d2a.png)

**Comment by qihangnet** [comment]
@Irian-Adappty I'll save this great screenshot to my album, 😄
