### ISSUE TITLE
Unable to install using Node v18

### ISSUE THREAD

**Issue by cvp2004** [BuilderIO/ai-shell#65]

**Comment by qihangnet** [comment]
Are you sure your installation command is the following:

``` bash
npm install -g @builder.io/ai-shell

```

and not

``` bash
npm install -g ai-shell
```

or something else?

**Comment by cvp2004** [comment]
Yes, I used "npm install -g @builder.io/ai-shell" command

**Comment by cvp2004** [comment]
PS C:\Users\cpara> npm install -g @builder.io/ai-shell
ParserError:
Line |
   1 |  npm install -g @builder.io/ai-shell
     |                 ~~~~~~~~
     | The splatting operator '@' cannot be used to reference variables in an expression. '@builder' can be used only
     | as an argument to a command. To reference variables in an expression use '$builder'.
PS C:\Users\cpara>

**Comment by AlaEddineBoughanmmi** [comment]
You need to escape the @ character not, sure on windows but try this:

```
npm install -g '@builder.io/ai-shell'
```

**Comment by cvp2004** [comment]
Thank you very much.

The solution worked.

**Comment by SaidTorres3** [comment]
Also, it works if you run it in CMD instead of PowerShell.
