### ISSUE TITLE
Add error message for missing argument

### ISSUE THREAD

**Issue by AhmedElTabarani** [BuilderIO/ai-shell#66]
```bash
λ npm exec ai
C:\Users\eltab\AppData\Local\npm-cache\_npx\afbc0d24890c4360\node_modules\ai\bin\ai.js:5
if (!args || args[0].split("/").length !== 2)
```

I think should send a nice message if the user doesn't send any argument

**Comment by steve8708** [comment]
I'm not fully understanding this, can you elaborate? for instance if you just type `ai` you get the interative mode:

```bash
➜ ai                          

┌  AI Shell
│
◆  What would you like me to to do?
│  e.g. list js files
└

```

**Comment by AhmedElTabarani** [comment]
Sorry, this was my mistake, this error happens when I use `npm exec ai`  without installing `@builder.io/ai-shell` globally first
