### ISSUE TITLE
 I get the same error even when I try to set the API key, "Please set your OpenAI API key ..."

### ISSUE THREAD

**Issue by AhmedElTabarani** [BuilderIO/ai-shell#69]
![image](https://user-images.githubusercontent.com/69223584/236105012-c963146a-d964-4ade-96fa-fb74621721d0.png)

**Comment by SohelIslamImran** [comment]
Same

**Comment by zahrevsky** [comment]
I've received the same error on 0.1.20, downgrading to 0.1.19 helped. 

Error occurs right after installation, meaning I haven't ran this tool with a configured token. Also `ai config` without args returns the same error as well. Hope this helps.

**Comment by qihangnet** [comment]
Sorry, this is my fault. I will submit a new PR to fix it today.

**Comment by qihangnet** [comment]
PR #71 has been submitted and is awaiting merging to release a new version.

**Comment by steve8708** [comment]
Show now be fixed in v0.1.21!
