### ISSUE TITLE
Cant determine os when termux is used on andriod 

### ISSUE THREAD

**Issue by codetheo75** [BuilderIO/ai-shell#74]

**Comment by AlaEddineBoughanmmi** [comment]
Its a missing feature with the package @nexssp/os  that we use to determn the os name. i raised an issue on their repo  https://github.com/nexssp/os/issues/7

**Comment by mapoart** [comment]
@AlaEddineBoughanmmi Guys - This is now fixed. Please upgrade to the latest version. Thanks for reporting the issue.
