### ISSUE TITLE
Shell option should be set for command execution with multiple processes and pipes to work

### ISSUE THREAD

**Issue by jpxd** [BuilderIO/ai-shell#8]
Thanks for this cool tool!

Often I need a combination of multiple commands e.g. with grep / jq etc.
For this ChatGPT outputs correct commands with pipes, but they don't work with `ai-shell` since it just executes one process without the shell support for pipes. Since `execa` is used this can simply be fixed by using the shell-flag.

See https://github.com/sindresorhus/execa#shell-syntax and https://github.com/sindresorhus/execa#shell for more information.

Here is an example for a perfectly fine command which works when pasted directly into bash or zsh but doesn't work with ai-shell:
<img width="962" alt="Bildschirm­foto 2023-04-07 um 12 22 39" src="https://user-images.githubusercontent.com/10384363/230593368-399f5fbf-470e-41e5-b9ad-f3c0000e6a2f.png">

**Comment by steve8708** [comment]
Agreed with this, interested in sending a pull request?

**Comment by jpxd** [comment]
PR sent :)
